### ISSUE TITLE
이슈 및 의견 드려봅니다.

### ISSUE THREAD

**Issue by lightria** [junimiso04/Bandit#2]
**버그**
- 로그인 비밀번호 오류
영어, 숫자 조합으로 비밀번호를 입력하고 로그인 하면 "비밀번호는 8자 이상, 20자 이하의 ~~" 라고 메시지가 나옵니다.
그런데 이상하게 한번 로그인 하면 로그인이 잘 됩니다.

- 핀 입력시 응답 없음
핀을 입력하고 나면 이유 없이 응답 없음이 뜹니다. (시간 지나면 풀립니다.)

- 설정 저장 안됨
config 파일이 분명 있는 것 같은데 설정 저장이 안됩니다.

**의견**
- 비밀번호 숨기기
대부분 개인 컴퓨터에서 사용하겠지만, 혹시 모르니 기본적으로는 숨길 수 있게 해주시길 바랍니다.

- 백그라운드
창을 닫고 작업 표시줄의 트레이 아이콘에서 실행이 가능하다면 좋을 것 같습니다.

---

사흘 동안 비주얼 베이직 Selenium 으로 밴드 출첵 코드 짜다가 빡쳐서 왔더니 이렇게 좋은 프로그램이 있을 줄은 상상도 못했습니다..
앞으로는 꿀잠 자겠습니다... 정말 감사드립니다...

**Comment by junimiso04** [comment]
- 로그인 및 비밀번호 입력 오류
비밀번호 입력 후 Enter 키를 누를 때에 입력된 비밀번호 값이 로그인 메소드에 제대로 전달되지 못하는 오류가 있었습니다. 이 오류는 차후 버전에서 수정될 예정입니다.

- 핀 입력 시 응답 없음
현재 버전(v1.0.0)에서는 모든 웹 작업들을 동기 방식으로 처리하고 있습니다. 따라서 웹 작업 중에는 UI 갱신이 이루어지지 못해서 응답없음이 발생하게 됩니다. 이쪽 부분에 관해서는 차후 비동기 처리가 완료되게 되면 사라지게 될 것입니다.

- 설정 저장 안됨
설정 저장 문제에 관해서는 config이 아니라 Json.NET을(를) 사용해 Json 파일로 저장할 계획이었고, 초기 버전에서 제공될 기능이었지만 제가 까먹고 추가를 안해버리는 바람에 차후 버전에서 제공될 예정입니다.

- 비밀번호 보안과 관련한 문제
이 부분은 저도 확실히 인지를 하고 있었습니다만, 초기 버전은 테스트용이기도 하고 보안을 위한 로직이 생각보다 설계가 어려워서 차후 버전으로 미뤄지게 되었습니다. 차후 버전에서는 PasswordBox와(과) SecureString을(를) 이용하여 더 안전하게 비밀번호를 처리할 예정입니다.

- 트레이 아이콘
트레이 아이콘은 제가 미쳐 생각하지 못했던 아이디어인데, lightria님 덕분에 좋은 기능을 추가할 수 있게 되었습니다. 트레이 아이콘으로의 전환 기능은 차후 버전에서 제공하도록 하겠습니다.


※ 제 프로그램을 사용해주시고 이슈까지 남겨주셔서 정말 감사합니다! 솔직히 남이 쓸거라고는 생각하지 못해서 막만들어낸 감이 없잖아 있었는데, lightria님 덕분에 많은 보람을 느꼈고 더 잘 만들어봐야겠다는 생각이 들었네요. 앞으로 빠른 시간 안에 더 나은 버전을 공개하도록 하겠습니다-!

**Comment by lightria** [comment]
역시 개발자는 밤 늦게 커밋 올리는게 일상인가 봅니다 ㅋㅋㅋ
전체적인 구조 변경은 다음 릴리즈를 기다리면 될까요?

**Comment by junimiso04** [comment]
잠이 안와서 일단 비밀번호쪽만 수정했네요 ㅎㅎ
아마 일단 시간 지정 쪽에 문제가 있어서 그쪽 부분부터 먼저 수정을 하고 난 다음에 구조 변경이랑 비동기 처리를 하려고 생각중이에요.
구조 변경 부분에서 시간이 좀 걸릴것 같고, 자잘한 업데이트까지 생각하면 2~3 릴리즈 안에 완료될것 같아요!
